### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by amarildolucas** [arthurpalves/badgy#6]
When I followed the installation instructions for SPM (Swift), it not worked as expected. I needed to run the followed commands to install it and enable it to be run from anywhere on the command line on my Mac:

```bash
$ swift build -c release
$ cd .build/release
$ cp -f badgy /usr/local/bin/badgy
```

**Comment by arthurpalves** [comment]
As instructed it’s meant to be used directly with `swift run badgy` from source. Also, the step you mentioned is already done in the `make install` process
